### ISSUE TITLE
[Tech]: Implement Technical Committee (Governance)

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-parachain#129] opened 2023-08-29 12:41 UTC
### Problem statement

We currently don't have any governance body on the Kusama parachain. We need to implement the same bodies as we have on the mainnet to manage governance operations on the network.

### Definition of Done

- [ ] Technical committee implemented the same way as on mainnet

**Comment by bgodlin** [comment] 2023-08-30 11:06
Has to be checked for duplication with https://github.com/sora-xor/sora2-parachain/issues/127

**Comment by bgodlin** [comment] 2023-09-14 11:10
Duplicate of #127

**Closed as not planned** 2023-09-14 11:10 UTC
Labels: tech
